#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'
networks:
  ca-network:

services:

  ca-cli:
     image: hyperledger/fabric-ca
     container_name: ca-cli
     environment:
       - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
     working_dir: /etc/hyperledger/fabric-ca-server
     volumes:
       - './ca-cli:/etc/hyperledger/fabric-ca-server'
     command: /bin/sh -c "while true; do echo hello world; sleep 10; done"
     networks:
       - ca-network

  orderer-ca:
         image: hyperledger/fabric-ca
         container_name: orderer-ca
         environment:
           - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
           - FABRIC_CA_SERVER_TLS_ENABLED=false
           - FABRIC_CA_SERVER_DEBUG=false
         volumes:
           - './orderer-ca:/etc/hyperledger/fabric-ca-server'
         command: sh -c 'fabric-ca-server start -b admin:adminpw'
         networks:
           - ca-network
           
  tls-ca:
         image: hyperledger/fabric-ca
         container_name: tls-ca
         environment:
           - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
           - FABRIC_CA_SERVER_TLS_ENABLED=false
           - FABRIC_CA_SERVER_DEBUG=false
         volumes:
           - './tls-ca:/etc/hyperledger/fabric-ca-server'
         command: sh -c 'fabric-ca-server start -b admin:adminpw'
         networks:
           - ca-network
           
  diagnose-ca:
         image: hyperledger/fabric-ca
         container_name: diagnose-ca
         environment:
           - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
           - FABRIC_CA_SERVER_TLS_ENABLED=false
           - FABRIC_CA_SERVER_DEBUG=false
         volumes:
           - './diagnose-ca:/etc/hyperledger/fabric-ca-server'
         command: sh -c 'fabric-ca-server start -b admin:adminpw'
         networks:
           - ca-network
           
