# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer1.test.ejubc.com:
    container_name: orderer1.test.ejubc.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/test.ejubc.com/orderers/orderer1.test.ejubc.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/test.ejubc.com/orderers/orderer1.test.ejubc.com/tls/:/var/hyperledger/orderer/tls
        - orderer1.test.ejubc.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.diagnose.test.ejubc.com:
    container_name: peer0.diagnose.test.ejubc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.diagnose.test.ejubc.com
      - CORE_PEER_ADDRESS=peer0.diagnose.test.ejubc.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.diagnose.test.ejubc.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.diagnose.test.ejubc.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.diagnose.test.ejubc.com:7051
      - CORE_PEER_LOCALMSPID=diagnoseMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/diagnose.test.ejubc.com/peers/peer0.diagnose.test.ejubc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/diagnose.test.ejubc.com/peers/peer0.diagnose.test.ejubc.com/tls:/etc/hyperledger/fabric/tls
        - peer0.diagnose.test.ejubc.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.diagnose.test.ejubc.com:
    container_name: peer1.diagnose.test.ejubc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.diagnose.test.ejubc.com
      - CORE_PEER_ADDRESS=peer1.diagnose.test.ejubc.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.diagnose.test.ejubc.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.diagnose.test.ejubc.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.diagnose.test.ejubc.com:7051
      - CORE_PEER_LOCALMSPID=diagnoseMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/diagnose.test.ejubc.com/peers/peer1.diagnose.test.ejubc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/diagnose.test.ejubc.com/peers/peer1.diagnose.test.ejubc.com/tls:/etc/hyperledger/fabric/tls
        - peer1.diagnose.test.ejubc.com:/var/hyperledger/production

    ports:
      - 8051:8051
